Task 3
Naooki/nodejs-aws-be pull request #1
Opened 2021-04-06 20:21 UTC by Naooki

### What was done?
- Products-service (2 lambdas + FE integration)
- all additional tasks (including swagger doc)

### Link to product-service API:
GET - https://uhvqepz8rb.execute-api.eu-west-1.amazonaws.com/dev/products/{productId}
GET - https://uhvqepz8rb.execute-api.eu-west-1.amazonaws.com/dev/products

### LInk to FE MR:
https://github.com/Naooki/nodejs-aws-fe/pull/2

2021-04-09 17:08 UTC, ikushlianski requested changes
Please change the status code 400 to 500 in the `catch` block and add validation. Otherwise good work! :muscle:

2021-04-09 17:08 UTC, ikushlianski commented on packages/product-service/src/handlers/getProductById.ts
> +    const product = await getProductById(productId);
I'd add the validation of `productId` param

2021-04-09 17:08 UTC, ikushlianski commented on packages/product-service/src/handlers/getProductById.ts
> +    const statusCode = 400;
If you have a DB connection failure or sth like this, we will get into this `catch` block, but we should return `500`. 

We could return `400` in the `try` block when validation fails.

2021-04-09 17:08 UTC, ikushlianski commented on packages/product-service/src/handlers/getProductsList.spec.ts
> +    const resp: any = await getProductsListHandler(event, null, null);
I'd test not the handler (infrastructure logic), but focus on the underlying service that does business or application logic (validation, fetching from db, remapping...)

2021-04-10 08:14 UTC, gultyaev commented on packages/product-service/src/handlers/getProductById.ts
> +      };
I'd advice creating some function so not to create this object from scratch every time. This would increase the readability.

2021-04-10 08:16 UTC, gultyaev commented on packages/product-service/src/handlers/getProductsList.spec.ts
> +    } as any;
I think it's incorrect to use status code 400 in this case. Also, the method should be responsible for returning of an array of products and therefore the test's description is misleading (it says "the product")

2021-04-18 18:46 UTC, merged